# Generated by Django 3.1.12 on 2021-08-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units',
            new_name='measurement_unit',
        ),
    ]
