# Generated by Django 3.1.12 on 2021-08-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210825_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
