version: '3.3'
volumes:
  postgres_data:
  static_value:
  media_value:
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  # Поскольку у нас нет необходимости каждый раз пересобирать фронт, то воспользуемся заранее загруженным образом с хаба
  frontend:
    image: andyi95/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/static/
      - media_value:/media/
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always
    depends_on:
      - back
      - frontend
    env_file:
      - ./.env

  back:
    image: andyi95/foodgram_project
    restart: always
    volumes:
      - static_value:/code/static
      - media_value:/code/media
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  redis:
    image: redis:6.2.5
