# Generated by Django 3.1.12 on 2021-08-27 13:55

import django.contrib.auth.models
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210822_1843'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('ext_objects', users.models.CustomUserManager()),
            ],
        ),
    ]
